import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Metadata } from 'next'
import PapersClient from './PapersClient'

export const metadata: Metadata = {
  title: 'Papers — Archimedes Research Lab',
  description: 'Publication-ready manuscripts generated by the autonomous research pipeline.',
}

export default function PapersPage() {
  return (
    <main>
      <Navbar />
      <PapersClient />
      <Footer />
    </main>
  )
}
